### ISSUE TITLE
Bad (i.e. old) Link for "Report the problem to xBlackCat" in IDEA exception dialog

### ISSUE THREAD

**Issue by Javaru** [xBlackCat/favoritefolders-idea-plugin#4]
When an exception occurs, and IDEA reports it via the "IDE Fatal Errors" dialog, the link in the phrase "Please report the problem to xBlackCat" directs to your old repo at http://code.google.com/p/favoritefolders-idea-plugin  I believe this address is picked up from the `url` attribute of the `<vendor>` element in the `plugin.xml`.

**Comment by xBlackCat** [comment]
Fixed in v1.3.2
